#!/bin/bash

# Script to show vpn connections and show as a system notification

output=`echo "";echo "---- ppp/tun/vpn connections"; echo "";ifconfig | egrep -A7 "ppp|tun|vpn";echo "";echo "---- NetworkManager Connections ----";echo "";nmcli connection show --active | grep 'vpn'`

zenity --notification --text="`printf "====================VPN Status====================\n$output"`"


